package cn.he.zhao.bbs.entity;

import cn.he.zhao.bbs.entityUtil.my.User;
import cn.he.zhao.bbs.spring.SpringUtil;
import cn.he.zhao.bbs.util.Symphonys;
import org.apache.commons.lang.StringUtils;
import org.json.JSONObject;

public class UserExt {

    private String oid;
    private Integer userNo;
    private String userEmail;
    private String userName;
    private String userPassword;
    private String userNickname;
    private String userTags;
    private String userURL;
    private String userQQ;
    private String userIntro;
    private Integer userAvatarType;
    private String userAvatarURL;
    private String userB3Key;
    private String userB3ClientAddArticleURL;
    private String userB3ClientUpdateArticleURL;
    private String userB3ClientAddCommentURL;
    private String userRole;
    private Long userUpdateTime;
    private String userCity;
    private String userCountry;
    private String userProvince;
    private String userSkin;
    private String userMobileSkin;
    private Long userCheckinTime;
    private Integer userLongestCheckinStreakStart;
    private Integer userLongestCheckinStreakEnd;
    private Integer userCurrentCheckinStreakStart;
    private Integer userCurrentCheckinStreakEnd;
    private Integer userLongestCheckinStreak;
    private Integer userCurrentCheckinStreak;
    private Integer userArticleCount;
    private Integer userCommentCount;
    private Integer userTagCount;
    private Integer userStatus;
    private Integer userPoint;
    private Integer userUsedPoint;
    private Integer userJoinPointRank;
    private Integer userJoinUsedPointRank;
    private String userOnlineFlag;
    private Long userLatestArticleTime;
    private Long userLatestCmtTime;
    private Long userLatestLoginTime;
    private Integer userAppRole;
    private Integer userCommentViewMode;
    private String syncWithSymphonyClient;
    private Integer userGeoStatus;
    private Integer userAvatarViewMode;
    private Integer userListPageSize;
    private Integer userListViewMode;
    private Integer userForgeLinkStatus;
    private Integer userBreezemoonStatus;
    private Integer userPointStatus;
    private Integer userFollowerStatus;
    private Integer userFollowingArticleStatus;
    private Integer userWatchingArticleStatus;
    private Integer userFollowingTagStatus;
    private Integer userFollowingUserStatus;
    private Integer userCommentStatus;
    private Integer userArticleStatus;
    private Integer userOnlineStatus;
    private Integer userTimelineStatus;
    private Integer userUAStatus;
    private Integer userNotifyStatus;
    private Integer userSubMailStatus;
    private Long userSubMailSendTime;
    private Integer userKeyboardShortcutsStatus;
    private Integer userReplyWatchArticleStatus;
    private Integer userGuideStep;
    private String userLanguage;
    private String userTimezone;

}
