server:
    port: 8777
#    context-path: bbs

spring:
    application:
        name: bbs
    freemarker:
        template-loader-path: classpath:/templates/
        suffix: .ftl

BBS:
    StaticServePath: classpath:/templates/
    RuntimeMode: dev
    staticResourceVersion: 201304262200

mybatis:
    type-aliases-package: cn.he.zhao.bbs.entity

#    messages:
#        basename: lang
#        cache-seconds: 3600
#        encoding: UTF-8